### ISSUE TITLE
it can't deal with scaffold ?

### ISSUE THREAD

**Issue by amywen1** [gamcil/genome2json#4]
`g2j -fa GRCh37.p13.genome.fa -gff homo_sapiens.GRCh37.Regulatory_Build.regulatory_features.20191101.gff -o OUTPUT
`
[20:48:30] INFO - Parsing files...
[20:48:30] INFO - GFF: homo_sapiens.GRCh37.Regulatory_Build.regulatory_features.20191101.gff
[20:48:30] INFO - FASTA: GRCh37.p13.genome.fa
Traceback (most recent call last):
  File "/home/yangwq/miniconda3/bin/g2j", line 8, in <module>
    sys.exit(run())
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/main.py", line 58, in run
    parse(
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/main.py", line 36, in parse
    organism = gff3.parse(
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/gff3.py", line 110, in parse
    scaffolds=[
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/gff3.py", line 113, in <listcomp>
    sequences[accession] if save_scaffold_sequence else "",
**KeyError: 'GL000191.1'**

**Comment by gamcil** [comment]
It should be able to, are you sure the scaffold names in your FASTA file match the scaffold names in the GFF file? You can also try parsing the same region in GenBank format.

It might choke on such a large file though, I have only tested it on smaller microbial genomes.
