### ISSUE TITLE
human fasta convert json

### ISSUE THREAD

**Issue by amywen1** [gamcil/genome2json#5]
Hi, maybe genome2json can't deal with the fasta of human. I test genome2json with  the the chr1 of consistent version of human GRCh37(http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz , ftp://ftp.ensembl.org/pub/grch37/current/regulation/homo_sapiens/homo_sapiens.GRCh37.Regulatory_Build.regulatory_features.20191101.gff.gz ). I added 'chr' in gff, to Change chromosome from 1 to chr1, but the error still appears:
[07:49:42] INFO - Parsing files...
[07:49:42] INFO - GFF: b37.gff
[07:49:42] INFO - FASTA: b37.fa
Traceback (most recent call last):
  File "/home/yangwq/miniconda3/bin/g2j", line 8, in <module>
    sys.exit(run())
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/main.py", line 58, in run
    parse(
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/main.py", line 36, in parse
    organism = gff3.parse(
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/gff3.py", line 110, in parse
    scaffolds=[
  File "/home/yangwq/miniconda3/lib/python3.8/site-packages/g2j/gff3.py", line 113, in <listcomp>
    sequences[accession] if save_scaffold_sequence else "",
**KeyError: 'chr1'**

**Comment by gamcil** [comment]
I think this is because the FASTA parser doesn't trim the headers of sequences, so the GFF will not match it.
e.g. `GL000237.1 dna:supercontig supercontig::GL000237.1:1:45867:1` is saved instead of just `GL000237.1`

In the meantime, you can pre-process the FASTA file like:
`sed -e 's/ .*$//' human_g1k_v37.fasta > human_trimmed.fasta`

This will delete anything after the scaffold accession. It worked for me on those files after doing that :)
